export const Icons = {
    profile: require("./profile.png"),
    pencil: require("./pencil.png"),
    website: require("./website.png"),
    favorite: require("./favorite.png"),
    foodtruck: require("./foodtruck.png"),
    arrowLeft: require("./arrow-left.png"),
    home: require("./home.png"),
    search: require("./search.png"),
    location: require("./location.png"),
    customer: require("./customer.png"),
    vendor: require("./vendor.png"),
    restaurant: require("./restaurant.png"),
    restaurant2: require("./restaurant2.png"),
    heartFilled: require("./heart-filled.png"),
    heartOutline: require("./heart-outline.png"),
    star: require("./star.png"),
    starOutline: require("./star-outline.png"),
    trash: require("./trash.png"),
    instagram: require("./instagram.png"),
    whatsapp: require("./whatsapp.png"),
    websiteIcon: require("./website.png"),
    edit: require("./edit.png"),
    Settings: require("./Settings.png"),
    Help: require("./Help.png"),
    Privacy: require("./Privacy.png"),
};